version: '3.8'

services:

  app:
    build: .
    command: python -u mon_app.py
    ports:
      - 5000:5000
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: mongo:latest
   
    ports:
      - 27017:27017